# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180311_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='usersaaa/%Y/%m/%d'),
        ),
    ]
