# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180312_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='usersaaa12324/%Y/%m/%d'),
        ),
    ]
